build: *
	stack build

ch24:
	ghcid -c 'stack ghci --main-is haskellbook:exe:haskellbook' --test 'Chapter24.main'

ch27:
	ghcid -c 'stack ghci --main-is haskellbook:exe:haskellbook' --test 'Chapter27.main'

ch28:
	ghcid -c 'stack ghci --main-is haskellbook:exe:haskellbook' --test 'Chapter28.ghcid'

default: build
